let commentsData = [
  {
    name: "Animesh Singh",
    text: "This is very good.",
    replies: [
      {
        name: "Animesh Singh",
        text: "This looks amazing.",
        replies: [
          {
            name: "Animesh Singh",
            text: "This looks amazing.",
            replies: [
              {
                name: "Animesh Singh",
                text: "This looks amazing.",
                replies: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Animesh Singh",
    text: "This is very nice.",
    replies: [],
  },
  {
    name: "Animesh Singh",
    text: "This is very cool.",
    replies: [],
  },
  {
    name: "Animesh Singh",
    text: "This looks amazing.",
    replies: [],
  },
  {
    name: "Animesh Singh",
    text: "I'm really impressed with this.",
    replies: [],
  },
  {
    name: "Animesh Singh",
    text: "This turned out fantastic.",
    replies: [],
  },
];

var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

const comments = [
  "Awesome video! Loved it! 🔥",
  "This is great! Keep it up! 😊",
  "I learned so much from this! Thanks! 🙏",
  "Not what I expected, but still good.",
  "Could you explain this part in more detail? 🤔",
  "Not sure if I agree with this. 🤷‍♂️",
  "Please make more content like this! 👍",
  "I wish the audio was clearer. 😕",
  "Great editing, but the topic is not for me.",
  "This was a bit boring. Sorry! 😬",
];

export function getRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}
export const getRandomComment = () => {
  return comments[Math.floor(Math.random() * comments.length)];
};
export default commentsData;
